# -*- coding: utf-8 -*-
"""BlockE2T.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fk7UqVxM63wdmq7qPO5kfVQJ_Fvv9o72
"""

# ==========================================================
# BlockE2T-MORL
# Blockchain-Enabled Multi-Objective Reinforcement Learning
# ==========================================================

import os
import math
import copy
import hashlib
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from collections import deque
from dataclasses import dataclass

# ==========================================================
# Reproducibility
# ==========================================================

SEED = 42

np.random.seed(SEED)
torch.manual_seed(SEED)

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Device:", DEVICE)

# ==========================================================
# Environment Parameters
# ==========================================================

GRID_SIZE = 10

NUM_AGENTS = 20

EPISODES = 200

MAX_STEPS = 100

OBSTACLE_RATIO = 0.15

COMMUNICATION_RANGE = 5

OBSERVATION_RANGE = 2

# ==========================================================
# Trust Parameters
# ==========================================================

TRUST_ALPHA = 0.7

TRUST_FLOOR = 0.1

INITIAL_TRUST = 0.5

# ==========================================================
# MORL Weights
# ==========================================================

W_ENERGY = 0.35

W_LATENCY = 0.35

W_SECURITY = 0.30

# ==========================================================
# RL Parameters
# ==========================================================

GAMMA = 0.99

ACTOR_LR = 1e-4

CRITIC_LR = 1e-3

LOCAL_EPOCHS = 5

# ==========================================================
# Adversarial Configuration
# ==========================================================

ADVERSARY_RATIO = 0.20

class DeterministicGridGenerator:

    def __init__(self, size):

        self.size = size

    def generate(self):

        grid = np.zeros((self.size, self.size))

        obstacle_locations = [

            (2,2),(2,3),(2,4),

            (4,5),(5,5),(6,5),

            (7,2),(7,3),

            (1,7),(2,7),

            (5,8),(6,8)

        ]

        for r,c in obstacle_locations:

            grid[r,c] = -1

        return grid

class TrustBlock:

    def __init__(self,
                 agent_id,
                 trust_score,
                 validation_score,
                 previous_hash):

        self.agent_id = agent_id

        self.trust_score = trust_score

        self.validation_score = validation_score

        self.previous_hash = previous_hash

        self.current_hash = self.compute_hash()

    def compute_hash(self):

        record = f"{self.agent_id}" \
                 f"{self.trust_score}" \
                 f"{self.validation_score}" \
                 f"{self.previous_hash}"

        return hashlib.sha256(
            record.encode()
        ).hexdigest()

class TrustLedger:

    def __init__(self):

        self.chain = []

    def add_record(self,
                   agent_id,
                   trust_score,
                   validation_score):

        prev_hash = "GENESIS"

        if len(self.chain) > 0:

            prev_hash = self.chain[-1].current_hash

        block = TrustBlock(
            agent_id,
            trust_score,
            validation_score,
            prev_hash
        )

        self.chain.append(block)

    def size(self):

        return len(self.chain)

class TrustManager:

    def __init__(self):

        self.trust_scores = {}

    def initialize_agent(self, agent_id):

        self.trust_scores[agent_id] = INITIAL_TRUST

    def update_trust(self,
                     agent_id,
                     validation_score):

        old = self.trust_scores[agent_id]

        new_score = (
            TRUST_ALPHA * old
            +
            (1 - TRUST_ALPHA) *
            validation_score
        )

        self.trust_scores[agent_id] = new_score

        return new_score

    def get_trust(self, agent_id):

        return self.trust_scores[agent_id]

# ==========================================================
# Agent State Representation
# S = (Position, Energy, Latency, Trust)
# ==========================================================

@dataclass
class AgentState:

    x: int
    y: int

    energy: float

    latency: float

    trust: float

# ==========================================================
# Smart Ambulance Agent
# ==========================================================

class AmbulanceAgent:

    def __init__(self,
                 agent_id,
                 start_pos):

        self.agent_id = agent_id

        self.position = start_pos

        self.energy = 200.0

        self.latency = 0.0

        self.trust = INITIAL_TRUST

        self.completed = False

        self.total_reward = 0

        self.steps = 0

    def reset(self, start_pos):

        self.position = start_pos

        self.energy = 200.0

        self.latency = 0.0

        self.completed = False

        self.total_reward = 0

        self.steps = 0

    def get_state(self):

        return AgentState(

            self.position[0],

            self.position[1],

            self.energy,

            self.latency,

            self.trust
        )

# ==========================================================
# Action Space
# ==========================================================

UP = 0
DOWN = 1
LEFT = 2
RIGHT = 3

ACTION_SIZE = 4

ACTION_MAP = {

    UP: (-1,0),

    DOWN: (1,0),

    LEFT: (0,-1),

    RIGHT: (0,1)
}

# ==========================================================
# Complete CloudGridEnvironment
# ==========================================================

class CloudGridEnvironment:

    def __init__(self):

        self.grid_size = GRID_SIZE

        self.grid = DeterministicGridGenerator(
            GRID_SIZE
        ).generate()

        self.start = (0, 0)

        self.goal = (9, 9)

        self.security_zones = self.create_security_zones()

        self.latency_map = self.create_latency_map()

    # ------------------------------------------------------

    def reset(self):

        return self.start

    # ------------------------------------------------------

    def inside_grid(self, x, y):

        return (
            0 <= x < self.grid_size
            and
            0 <= y < self.grid_size
        )

    # ------------------------------------------------------

    def is_obstacle(self, x, y):

        return self.grid[x, y] == -1

    # ------------------------------------------------------

    def create_security_zones(self):

        return {

            (3,3):0.4,

            (3,4):0.4,

            (6,6):0.5,

            (6,7):0.5,

            (8,3):0.6

        }

    # ------------------------------------------------------

    def create_latency_map(self):

        latency = np.zeros(
            (GRID_SIZE, GRID_SIZE)
        )

        for i in range(GRID_SIZE):

            for j in range(GRID_SIZE):

                latency[i, j] = (

                    5

                    + 0.5 * i

                    + 0.3 * j

                )

        return latency

    # ------------------------------------------------------

    def energy_cost(
        self,
        current,
        nxt
    ):

        distance = (

            abs(current[0] - nxt[0])

            +

            abs(current[1] - nxt[1])

        )

        return 1.5 * distance

    # ------------------------------------------------------

    def security_score(
        self,
        position
    ):

        if position in self.security_zones:

            return self.security_zones[position]

        return 1.0

    # ------------------------------------------------------

    def step(
        self,
        agent,
        action
    ):

        dx, dy = ACTION_MAP[action]

        x, y = agent.position

        nx = x + dx

        ny = y + dy

        # Boundary

        if not self.inside_grid(nx, ny):

            return (

                agent.position,

                -25,

                False,

                {

                    "collision": True,

                    "energy": 0,

                    "latency": 0,

                    "security": 0

                }

            )

        # Obstacle

        if self.is_obstacle(nx, ny):

            return (

                agent.position,

                -25,

                False,

                {

                    "collision": True,

                    "energy": 0,

                    "latency": 0,

                    "security": 0

                }

            )

        next_position = (nx, ny)

        energy_used = self.energy_cost(

            agent.position,

            next_position

        )

        latency = self.latency_map[nx, ny]

        security = self.security_score(

            next_position

        )

        agent.position = next_position

        agent.energy -= energy_used

        agent.latency += latency

        done = False

        reward = -1

        if next_position == self.goal:

            done = True

            reward = 100

        info = {

            "energy": energy_used,

            "latency": latency,

            "security": security,

            "collision": False

        }

        return (

            next_position,

            reward,

            done,

            info

        )

def create_security_zones(self):

        zones = {

            (3,3):0.4,

            (3,4):0.4,

            (6,6):0.5,

            (6,7):0.5,

            (8,3):0.6

        }

        return zones

def create_latency_map(self):

        latency = np.zeros(
            (GRID_SIZE,GRID_SIZE)
        )

        for i in range(GRID_SIZE):

            for j in range(GRID_SIZE):

                latency[i,j] = (

                    5

                    +

                    0.5*i

                    +

                    0.3*j

                )

        return latency

def energy_cost(self,
                    current,
                    nxt):

        distance = (

            abs(current[0]-nxt[0])

            +

            abs(current[1]-nxt[1])

        )

        return 1.5 * distance

def security_score(self,
                       position):

        if position in self.security_zones:

            return self.security_zones[position]

        return 1.0

def step(self,
             agent,
             action):

        dx,dy = ACTION_MAP[action]

        x,y = agent.position

        nx = x + dx

        ny = y + dy

        if not self.inside_grid(nx,ny):

            return (
                agent.position,
                -25,
                False,
                {"collision":True}
            )

        if self.is_obstacle(nx,ny):

            return (
                agent.position,
                -25,
                False,
                {"collision":True}
            )

        next_position = (nx,ny)

        energy_used = self.energy_cost(
            agent.position,
            next_position
        )

        latency = self.latency_map[
            nx,ny
        ]

        security = self.security_score(
            next_position
        )

        agent.energy -= energy_used

        agent.latency += latency

        agent.position = next_position

        done = False

        if next_position == self.goal:

            done = True

            reward = 100

        else:

            reward = -1

        info = {

            "energy":energy_used,

            "latency":latency,

            "security":security
        }

        return (
            next_position,
            reward,
            done,
            info
        )

class MORLReward:

    def compute(self,
                energy,
                latency,
                security,
                trust,
                reached_goal):

        energy_term = 1/(1+energy)

        latency_term = 1/(1+latency)

        security_term = security

        reward = (

            W_ENERGY
            *
            energy_term

            +

            W_LATENCY
            *
            latency_term

            +

            W_SECURITY
            *
            security_term

        )

        reward = reward * trust

        if reached_goal:

            reward += 100

        return reward

class AdversarialManager:

    def __init__(self,
                 num_agents,
                 ratio):

        self.num_agents = num_agents

        self.ratio = ratio

        self.adversaries = self.create()

    def create(self):

        count = int(
            self.num_agents *
            self.ratio
        )

        return list(
            range(count)
        )

    def is_adversarial(self,
                       agent_id):

        return (
            agent_id
            in
            self.adversaries
        )

env = CloudGridEnvironment()

reward_engine = MORLReward()

trust_manager = TrustManager()

ledger = TrustLedger()

agents = []

for i in range(NUM_AGENTS):

    trust_manager.initialize_agent(i)

    agent = AmbulanceAgent(

        agent_id=i,

        start_pos=(0,0)

    )

    agents.append(agent)

print(
    "Agents:",
    len(agents)
)

print(
    "Goal:",
    env.goal
)

env = CloudGridEnvironment()

reward_engine = MORLReward()

trust_manager = TrustManager()

ledger = TrustLedger()

agents = []

for i in range(NUM_AGENTS):

    trust_manager.initialize_agent(i)

    agent = AmbulanceAgent(

        agent_id=i,

        start_pos=(0,0)

    )

    agents.append(agent)

print(
    "Agents:",
    len(agents)
)

print(
    "Goal:",
    env.goal
)

# ==========================================================
# State Encoder
# ==========================================================

def state_to_tensor(agent_state):

    state = np.array([

        agent_state.x / GRID_SIZE,

        agent_state.y / GRID_SIZE,

        agent_state.energy / 200.0,

        agent_state.latency / 100.0,

        agent_state.trust

    ], dtype=np.float32)

    return torch.FloatTensor(state)

# ==========================================================
# Actor Network
# ==========================================================

class ActorNetwork(nn.Module):

    def __init__(self,
                 state_dim=5,
                 action_dim=4):

        super().__init__()

        self.fc1 = nn.Linear(
            state_dim,
            128
        )

        self.fc2 = nn.Linear(
            128,
            64
        )

        self.fc3 = nn.Linear(
            64,
            action_dim
        )

    def forward(self,x):

        x = F.relu(self.fc1(x))

        x = F.relu(self.fc2(x))

        logits = self.fc3(x)

        probs = F.softmax(
            logits,
            dim=-1
        )

        return probs

# ==========================================================
# Critic Network
# ==========================================================

class CriticNetwork(nn.Module):

    def __init__(self,
                 state_dim=5):

        super().__init__()

        self.fc1 = nn.Linear(
            state_dim,
            128
        )

        self.fc2 = nn.Linear(
            128,
            64
        )

        self.fc3 = nn.Linear(
            64,
            1
        )

    def forward(self,x):

        x = F.relu(self.fc1(x))

        x = F.relu(self.fc2(x))

        value = self.fc3(x)

        return value

# ==========================================================
# Experience Memory
# ==========================================================

class ExperienceBuffer:

    def __init__(self):

        self.clear()

    def clear(self):

        self.states = []

        self.actions = []

        self.rewards = []

        self.next_states = []

        self.dones = []

class BlockE2TMORLAgent:

    def __init__(self):

        self.actor = ActorNetwork().to(DEVICE)

        self.critic = CriticNetwork().to(DEVICE)

        self.actor_optimizer = optim.Adam(
            self.actor.parameters(),
            lr=ACTOR_LR
        )

        self.critic_optimizer = optim.Adam(
            self.critic.parameters(),
            lr=CRITIC_LR
        )

        self.memory = ExperienceBuffer()

    def select_action(self,state):

        state = state.unsqueeze(0).to(DEVICE)

        probs = self.actor(state)

        distribution = torch.distributions.Categorical(
            probs
        )

        action = distribution.sample()

        log_prob = distribution.log_prob(
            action
        )

        return action.item(), log_prob

    def store_transition(
        self,
        state,
        action,
        reward,
        next_state,
        done
    ):

        self.memory.states.append(state)

        self.memory.actions.append(action)

        self.memory.rewards.append(reward)

        self.memory.next_states.append(next_state)

        self.memory.dones.append(done)

    def compute_advantages(self):

        returns = []

        discounted_reward = 0

        for reward, done in zip(

            reversed(self.memory.rewards),

            reversed(self.memory.dones)

        ):

            if done:

                discounted_reward = 0

            discounted_reward = (
                reward
                +
                GAMMA * discounted_reward
            )

            returns.insert(
                0,
                discounted_reward
            )

        returns = torch.FloatTensor(
            returns
        ).to(DEVICE)

        states = torch.stack(
            self.memory.states
        ).to(DEVICE)

        values = self.critic(
            states
        ).squeeze()

        advantages = (
            returns
            -
            values.detach()
        )

        return returns, advantages

    def update(self, trust_factor=1.0):

        returns, advantages = \
            self.compute_advantages()

        states = torch.stack(
            self.memory.states
        ).to(DEVICE)

        actions = torch.LongTensor(
            self.memory.actions
        ).to(DEVICE)

        probs = self.actor(states)

        distribution = torch.distributions.Categorical(
            probs
        )

        log_probs = distribution.log_prob(
            actions
        )

        actor_loss = -(
            log_probs
            *
            advantages
            *
            trust_factor
        ).mean()

        values = self.critic(
            states
        ).squeeze()

        critic_loss = F.mse_loss(
            values,
            returns
        )

        self.actor_optimizer.zero_grad()

        actor_loss.backward()

        self.actor_optimizer.step()

        self.critic_optimizer.zero_grad()

        critic_loss.backward()

        self.critic_optimizer.step()

        self.memory.clear()

        return (
            actor_loss.item(),
            critic_loss.item()
        )

def select_action(self,state):

        state = state.unsqueeze(0).to(
            DEVICE
        )

        probs = self.actor(state)

        distribution = torch.distributions.Categorical(
            probs
        )

        action = distribution.sample()

        log_prob = distribution.log_prob(
            action
        )

        return (

            action.item(),

            log_prob
        )

def store_transition(self,
                         state,
                         action,
                         reward,
                         next_state,
                         done):

        self.memory.states.append(state)

        self.memory.actions.append(action)

        self.memory.rewards.append(reward)

        self.memory.next_states.append(
            next_state
        )

        self.memory.dones.append(done)

def compute_advantages(self):

        returns = []

        discounted_reward = 0

        for reward, done in zip(

            reversed(
                self.memory.rewards
            ),

            reversed(
                self.memory.dones
            )
        ):

            if done:

                discounted_reward = 0

            discounted_reward = (

                reward

                +

                GAMMA
                *
                discounted_reward
            )

            returns.insert(
                0,
                discounted_reward
            )

        returns = torch.FloatTensor(
            returns
        ).to(DEVICE)

        states = torch.stack(
            self.memory.states
        ).to(DEVICE)

        values = self.critic(
            states
        ).squeeze()

        advantages = (
            returns
            -
            values.detach()
        )

        return (

            returns,

            advantages
        )

def update(self,
               trust_factor=1.0):

        returns, advantages = \
            self.compute_advantages()

        states = torch.stack(
            self.memory.states
        ).to(DEVICE)

        actions = torch.LongTensor(
            self.memory.actions
        ).to(DEVICE)

        probs = self.actor(states)

        distribution = torch.distributions.Categorical(
            probs
        )

        log_probs = distribution.log_prob(
            actions
        )

        actor_loss = -(

            log_probs
            *
            advantages
            *
            trust_factor

        ).mean()

        values = self.critic(
            states
        ).squeeze()

        critic_loss = F.mse_loss(
            values,
            returns
        )

        self.actor_optimizer.zero_grad()

        actor_loss.backward()

        self.actor_optimizer.step()

        self.critic_optimizer.zero_grad()

        critic_loss.backward()

        self.critic_optimizer.step()

        self.memory.clear()

        return (

            actor_loss.item(),

            critic_loss.item()
        )

def update(self,
               trust_factor=1.0):

        returns, advantages = \
            self.compute_advantages()

        states = torch.stack(
            self.memory.states
        ).to(DEVICE)

        actions = torch.LongTensor(
            self.memory.actions
        ).to(DEVICE)

        probs = self.actor(states)

        distribution = torch.distributions.Categorical(
            probs
        )

        log_probs = distribution.log_prob(
            actions
        )

        actor_loss = -(

            log_probs
            *
            advantages
            *
            trust_factor

        ).mean()

        values = self.critic(
            states
        ).squeeze()

        critic_loss = F.mse_loss(
            values,
            returns
        )

        self.actor_optimizer.zero_grad()

        actor_loss.backward()

        self.actor_optimizer.step()

        self.critic_optimizer.zero_grad()

        critic_loss.backward()

        self.critic_optimizer.step()

        self.memory.clear()

        return (

            actor_loss.item(),

            critic_loss.item()
        )

# ==========================================================
# Local RL Agents
# ==========================================================

local_rl_agents = []

for i in range(NUM_AGENTS):

    learner = BlockE2TMORLAgent()

    local_rl_agents.append(
        learner
    )

print(
    "RL Agents:",
    len(local_rl_agents)
)

test_state = torch.rand(5)

agent = BlockE2TMORLAgent()

action, log_prob = \
    agent.select_action(
        test_state
    )

print(
    "Action:",
    action
)

agent = BlockE2TMORLAgent()

print(dir(agent))

# ==========================================================
# Extract Model Parameters
# ==========================================================

def get_model_parameters(model):

    return {

        k: v.clone().detach()

        for k,v in model.state_dict().items()
    }

# ==========================================================
# Compute Delta Theta
# ==========================================================

def compute_update(

    global_model,

    local_model

):

    delta = {}

    global_dict = global_model.state_dict()

    local_dict = local_model.state_dict()

    for key in global_dict.keys():

        delta[key] = (

            local_dict[key]

            -

            global_dict[key]

        )

    return delta

# ==========================================================
# Validation Score
# ==========================================================

class ValidationEngine:

    def validate(

        self,

        local_actor,

        reference_actors

    ):

        similarities = []

        local_params = \
            get_model_parameters(
                local_actor
            )

        for ref in reference_actors:

            ref_params = \
                get_model_parameters(
                    ref
                )

            score = 0

            count = 0

            for key in local_params:

                l = local_params[key].flatten()

                r = ref_params[key].flatten()

                cosine = F.cosine_similarity(

                    l.unsqueeze(0),

                    r.unsqueeze(0)

                ).item()

                score += cosine

                count += 1

            similarities.append(
                score/count
            )

        return np.mean(
            similarities
        )

# ==========================================================
# Trust Update
# ==========================================================

def trust_update(

    previous_trust,

    validation_score

):

    new_trust = (

        TRUST_ALPHA

        *

        previous_trust

        +

        (1-TRUST_ALPHA)

        *

        validation_score

    )

    return float(new_trust)

# ==========================================================
# Blockchain Trust Validator
# ==========================================================

class BlockchainValidator:

    def __init__(self):

        self.ledger = TrustLedger()

    def verify_update(

        self,

        agent_id,

        trust_score,

        validation_score

    ):

        updated_trust = trust_update(

            trust_score,

            validation_score

        )

        self.ledger.add_record(

            agent_id,

            updated_trust,

            validation_score

        )

        accepted = (

            updated_trust

            >=

            TRUST_FLOOR
        )

        return (

            accepted,

            updated_trust

        )

# ==========================================================
# Federated Averaging (FedAvg)
# ==========================================================

def federated_average(local_agents):

    global_actor = copy.deepcopy(
        local_agents[0].actor
    )

    global_state = global_actor.state_dict()

    for key in global_state.keys():

        weights = []

        for agent in local_agents:

            weights.append(
                agent.actor.state_dict()[key].float()
            )

        global_state[key] = torch.stack(
            weights,
            dim=0
        ).mean(dim=0)

    global_actor.load_state_dict(
        global_state
    )

    return global_actor

# ==========================================================
# Trusted FedAvg
# ==========================================================

def trusted_aggregation(

    local_agents,

    trust_scores

):

    trusted_agents = []

    for idx,agent in enumerate(

        local_agents

    ):

        if trust_scores[idx] >= TRUST_FLOOR:

            trusted_agents.append(
                agent
            )

    if len(trusted_agents) == 0:

        trusted_agents = local_agents

    return federated_average(

        trusted_agents
    )

# ==========================================================
# Global Model Distribution
# ==========================================================

def distribute_global_model(
    global_actor,
    local_agents
):

    global_weights = global_actor.state_dict()

    for agent in local_agents:

        agent.actor.load_state_dict(
            global_weights
        )

    return local_agents

validator = ValidationEngine()

blockchain_validator = \
    BlockchainValidator()

print(
    "Blockchain Layer Ready"
)

# ==========================================================
# Validation Test
# ==========================================================

validation_score = validator.validate(
    local_rl_agents[0].actor,
    [
        local_rl_agents[1].actor,
        local_rl_agents[2].actor,
        local_rl_agents[3].actor
    ]
)

print(
    "Validation Score:",
    round(validation_score, 4)
)

current_trust = 0.50

new_trust = trust_update(

    current_trust,

    validation_score

)

print(
    "Updated Trust:",
    round(
        new_trust,
        4
    )
)

print(
    "Ledger Size:",
    blockchain_validator.ledger.size()
)

print(type(local_rl_agents))
print(len(local_rl_agents))

global_model = federated_average(
    local_rl_agents
)

print(type(global_model))

CloudGridEnvironment
TrustManager
BlockchainValidator
BlockE2TMORLAgent
print(type(env))
print(type(local_rl_agents[0]))
print(type(local_rl_agents[0].actor))
print(type(blockchain_validator))

# ==========================================================
# Training Metrics
# ==========================================================

reward_history = []

energy_history = []

latency_history = []

trust_history = []

success_history = []

actor_loss_history = []

critic_loss_history = []

# ==========================================================
# Adversarial Manager
# ==========================================================

adversarial_manager = AdversarialManager(
    NUM_AGENTS,
    ADVERSARY_RATIO
)

print(
    "Adversarial Agents:",
    adversarial_manager.adversaries
)

env = CloudGridEnvironment()

print(dir(env))

def step(self, agent, action):

    dx, dy = ACTION_MAP[action]

    x, y = agent.position

    nx = x + dx
    ny = y + dy

    # Boundary check
    if not self.inside_grid(nx, ny):

        return (
            agent.position,
            -25,
            False,
            {
                "collision": True,
                "energy": 0,
                "latency": 0,
                "security": 0
            }
        )

    # Obstacle check
    if self.is_obstacle(nx, ny):

        return (
            agent.position,
            -25,
            False,
            {
                "collision": True,
                "energy": 0,
                "latency": 0,
                "security": 0
            }
        )

    next_position = (nx, ny)

    energy_used = self.energy_cost(
        agent.position,
        next_position
    )

    latency = self.latency_map[nx, ny]

    security = self.security_score(
        next_position
    )

    # Update agent state
    agent.position = next_position

    agent.energy -= energy_used

    agent.latency += latency

    done = False

    reward = -1

    if next_position == self.goal:

        done = True

        reward = 100

    info = {

        "energy": energy_used,

        "latency": latency,

        "security": security,

        "collision": False

    }

    return (
        next_position,
        reward,
        done,
        info
    )

# ==========================================================
# BlockE2T-MORL Training
# ==========================================================

for episode in range(EPISODES):

    episode_reward = 0

    episode_energy = 0

    episode_latency = 0

    episode_trust = []

    success_count = 0

    actor_losses = []

    critic_losses = []

    # ---------------------------------
    # Agent Training
    # ---------------------------------

    for agent_id in range(NUM_AGENTS):

        env.reset()

        ambulance = agents[agent_id]

        ambulance.reset((0,0))

        learner = local_rl_agents[agent_id]

        trust_score = trust_manager.get_trust(
            agent_id
        )

        ambulance.trust = trust_score

        for step in range(MAX_STEPS):

            state = state_to_tensor(
                ambulance.get_state()
            )

            action, _ = learner.select_action(
                state
            )

            next_pos, base_reward, done, info = \
                env.step(
                    ambulance,
                    action
                )

            security = info.get(
                "security",
                1.0
            )

            reward = reward_engine.compute(

                energy=info.get(
                    "energy",
                    1
                ),

                latency=info.get(
                    "latency",
                    1
                ),

                security=security,

                trust=trust_score,

                reached_goal=done

            )

            next_state = state_to_tensor(
                ambulance.get_state()
            )

            learner.store_transition(

                state,

                action,

                reward,

                next_state,

                done
            )

            episode_reward += reward

            episode_energy += info.get(
                "energy",
                0
            )

            episode_latency += info.get(
                "latency",
                0
            )

            if done:

                success_count += 1

                break

        # ---------------------------------
        # Local Actor-Critic Update
        # ---------------------------------

        if len(
            learner.memory.rewards
        ) > 0:

            actor_loss, critic_loss = \
                learner.update(
                    trust_factor=
                    trust_score
                )

            actor_losses.append(
                actor_loss
            )

            critic_losses.append(
                critic_loss
            )

        # ---------------------------------
        # Adversarial Behaviour
        # ---------------------------------

        if adversarial_manager.is_adversarial(
            agent_id
        ):

            validation_score = 0.2

        else:

            validation_score = 0.95

        new_trust = \
            trust_manager.update_trust(

                agent_id,

                validation_score

            )

        episode_trust.append(
            new_trust
        )

    # ---------------------------------
    # Federated Aggregation
    # ---------------------------------

    trust_scores = [

        trust_manager.get_trust(i)

        for i in range(NUM_AGENTS)

    ]

    global_model = trusted_aggregation(

        local_rl_agents,

        trust_scores

    )

    distribute_global_model(

        global_model,

        local_rl_agents

    )

    # ---------------------------------
    # Store Metrics
    # ---------------------------------

    reward_history.append(
        episode_reward
    )

    energy_history.append(
        episode_energy
        /
        NUM_AGENTS
    )

    latency_history.append(
        episode_latency
        /
        NUM_AGENTS
    )

    trust_history.append(
        np.mean(
            episode_trust
        )
    )

    success_history.append(

        success_count
        /
        NUM_AGENTS

    )

    actor_loss_history.append(

        np.mean(actor_losses)

        if actor_losses else 0

    )

    critic_loss_history.append(

        np.mean(critic_losses)

        if critic_losses else 0

    )

    # ---------------------------------
    # Progress
    # ---------------------------------

    if (episode + 1) % 20 == 0:

        print(

            f"Episode "

            f"{episode+1}/{EPISODES}"

            f" | Reward={episode_reward:.2f}"

            f" | Trust={trust_history[-1]:.3f}"

            f" | Success={success_history[-1]:.2f}"

        )

env = CloudGridEnvironment()

print(hasattr(env, "step"))
print(hasattr(env, "energy_cost"))
print(hasattr(env, "security_score"))
print(hasattr(env, "inside_grid"))
print(hasattr(env, "is_obstacle"))

print("\nTraining Completed\n")

print(
    "Final Reward:",
    reward_history[-1]
)

print(
    "Final Energy:",
    energy_history[-1]
)

print(
    "Final Latency:",
    latency_history[-1]
)

print(
    "Final Trust:",
    trust_history[-1]
)

print(
    "Final Success Rate:",
    success_history[-1]
)

print("="*50)

print("BlockE2T-MORL Final Results")

print("="*50)

print(
    "Final Reward:",
    round(reward_history[-1],2)
)

print(
    "Average Energy:",
    round(
        np.mean(energy_history[-20:]),
        2
    )
)

print(
    "Average Latency:",
    round(
        np.mean(latency_history[-20:]),
        2
    )
)

print(
    "Average Trust:",
    round(
        np.mean(trust_history[-20:]),
        3
    )
)

print(
    "Success Rate:",
    round(
        np.mean(success_history[-20:]),
        3
    )
)

plt.figure(figsize=(10,5))

plt.plot(
    energy_history,
    linewidth=2
)

plt.xlabel("Episode")

plt.ylabel("Energy Consumption")

plt.title(
    "Energy Consumption over Episodes"
)

plt.grid(True)

plt.show()

plt.figure(figsize=(10,5))

plt.plot(
    energy_history,
    linewidth=2
)

plt.xlabel("Episode")

plt.ylabel("Energy Consumption")

plt.title(
    "Energy Consumption over Episodes"
)

plt.grid(True)

plt.show()

plt.figure(figsize=(10,5))

plt.plot(
    latency_history,
    linewidth=2
)

plt.xlabel("Episode")

plt.ylabel("Latency")

plt.title(
    "Latency Reduction over Episodes"
)

plt.grid(True)

plt.show()

plt.figure(figsize=(10,5))

plt.plot(
    trust_history,
    linewidth=2
)

plt.xlabel("Episode")

plt.ylabel("Trust Score")

plt.title(
    "Trust Evolution During Learning"
)

plt.grid(True)

plt.show()

final_trust_scores = [

    trust_manager.get_trust(i)

    for i in range(NUM_AGENTS)

]

plt.figure(figsize=(8,5))

plt.hist(
    final_trust_scores,
    bins=10
)

plt.xlabel("Trust Score")

plt.ylabel("Frequency")

plt.title(
    "Final Trust Distribution"
)

plt.show()

plt.figure(figsize=(10,5))

plt.plot(
    reward_history,
    linewidth=2
)

plt.xlabel("Episode")

plt.ylabel("Cumulative Reward")

plt.title(
    "Reward Convergence"
)

plt.grid(True)

plt.show()

plt.figure(figsize=(10,5))

plt.plot(
    reward_history,
    linewidth=2
)

plt.xlabel("Episode")

plt.ylabel("Cumulative Reward")

plt.title(
    "Reward Convergence"
)

plt.grid(True)

plt.show()

plt.figure(figsize=(10,5))

plt.plot(
    success_history,
    linewidth=2
)

plt.xlabel("Episode")

plt.ylabel("Success Rate")

plt.title(
    "Success Rate Evolution"
)

plt.grid(True)

plt.show()

window = 20

convergence_episode = None

for i in range(
    window,
    len(reward_history)
):

    recent = reward_history[
        i-window:i
    ]

    if np.std(recent) < 5:

        convergence_episode = i

        break

print(
    "Estimated Convergence Episode:",
    convergence_episode
)

results = pd.DataFrame({

    "Metric":[

        "Energy",

        "Latency",

        "Trust",

        "Reward",

        "Success Rate"

    ],

    "Value":[

        np.mean(
            energy_history[-20:]
        ),

        np.mean(
            latency_history[-20:]
        ),

        np.mean(
            trust_history[-20:]
        ),

        np.mean(
            reward_history[-20:]
        ),

        np.mean(
            success_history[-20:]
        )

    ]

})

print(results)